spring:
    application:
        name: oauth2-server
    profiles:
        active: dev
    datasource:
        #type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false
        username: root
        password: tiger
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true


security:
    basic:
        enabled: false
    oauth2:
        resource:
            filter-order: 3

##服务启动后向eureka注册中心注册自己的服务
eureka:
    client:
        enabled: true
        healthcheck:
            enabled: true
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://wwj:123@localhost:8070/eureka/


##服务器端口
server:
    port: 8071