

#配置授权服务器
#security:
#    oauth2:
#        client:
#            clientId: client
#            clientSecret: secret
#            accessTokenUri: http://localhost:8071/oauth/access_token
#            userAuthorizationUri: http://localhost:8071/oauth/authorize
#            clientAuthenticationScheme: form