#获取git上的配置文件
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/sherryAndL/spring-cloud-config.git
          searchPaths: cloud-config-repo
          username: 1021679969@qq.com
          password: 3167565leon
  application:
    name: cloud-config-server

#注册服务中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://zlhost:8762/eureka/

server:
  port: 8888